# Entire ending dictionary including secret ending
endings = {
    "dragongem":
        "You take the Dragon's heart and grip it tightly. The Gem begins to shine brightly and the Power seems to flow right into your veins. You march to the gates of the Jakeobins and transform. Destroying everything once there. You take throne as the new King, the new power showing through your new grip on the Kingdom. This is what the Loyalists wanted, right? I'm just reclaiming my throne. Ending: Tyrant of Flame🔥",
        "nodragongem":
        "You took the dragon's heart and threw it on the ground. It shattered into million of pieces. 'Thank you, I am finally free from the cycle that has plagued us for centuries...' the dragon utters to you, as it passes. The Kingdom may still be in shambles but Peace may not be so far away. Ending: The Final Peacekeeper. 🌿 ",
        "executed":
        "You didn't just execute him. You made sure anyone you tried to defect again would be scared too. This is what must be done to ensure the victory of the Loyalists. Later that year, the siege of the castle was successful with many losses. The wheels of history turn by blood alone. Ending: Blade of Justice.⚔️",
        "noexecuted":
        """After just a few minutes of interrogation, the rat exposes a major weakness in the Jakeobin ranks. Within a few weeks, the Loyalists were able to secure a majority and coup their leader. Reclaiming your throne once and for all. Ending: The Rat Repays Its Debtors🐀""",
    "dragonraid": "You give the rat the gem and he begins to glow. The light becomes so bright that you can no longer see temporarily. When you regain your sight, a red dragon roughly 10 feet tall stands before you. You lead the dragon to the Jakeobin base and reck havoc on it. With the power of the gem, the Jakeobins had no chance. You reclaimed your throne and got a sweet new dragon pet. Ending: The Dragon's Heir🐉",
        "loud":
        "'That's what I'm talking about!', the mysterious figure cheers, taking you aback as you now question what you signed up for. 'The Plan is simple: I have 'acquired' some explosives that would be a perfect distraction to allow someone like yourself sneak in, grab info, and get out. With that, he was off. You followed him far behind and found him prepping. 'Now, This, this is the fun part', he said as he pushed the lever. The expolsions rattled you but with all the pursuing chaos. You were able to enter without a hitch. After returning from the Jakeobin base, the intel you gathered allowed the Loyalists to make quick work of the weakened Jakeobins. 'It's good to be back' Ending: 007 Tomorrow Never Dies.🔫",
        "stealthy":
        """The man sighs. 'Fair enough...' You sneak up to the castle, looking for a way in. 'Hey! What are you doing over there?', you hear a voice shout at you. 'Oi, mate! I'm new and I left my keys at home. Can you get me in? I have a meeting in 5 minutes!' 'Sure, Someone has to take care of the new hires.' Perfect, I just got a free ticket.'What did you say your name was?'
        'Jim Milton, they just transfered me from the base up in New Dalesville.'
        'Huh, I didn't even know they had a base in New Dalesville.'
        'It's a newer facility for sure.'
        You thank the man for escorting you and walk into a poorly lit room where there are countless papers strowed all around the walls and floor with circles and threaded lines that look like a madman's work. You walk in and gather as much as you can from the room, leaving it as fast as you entered in. Returning to the man, he thanks you greatly for gathering the intel and disturbing the Jakeobin progress on cracking down the Loyalists. 'Victory shall be ours soon.', he says before disappearing as quickly as he arrived. Ending: The Invisible Man 🙈 """,
    "ratspy": " You send in the rat with not very high hopes. After a few days, he returns much worse than he arrived. 'There's only one thing they gave me and you could probably guess what it was.... However, I did manage to overhear some plans. He says almost begging, realizing what the failed operation might mean for him. 'They plan on building a new base up in New Dalesville, to increase their influence in the area as well as cracking down on the revoultion brewing in the city. That's how we'll find out what they're planning. Ending: The Rat's Tale🐀",
        "trojanhorse":"""It was hard to craft a message that would be real enought for the civilization to believe it was a real message while also dodging high command intervention. After sending the message, you waited. Was this worth it? What if you got caught? Then it came, a notification on your computer. Access Granted. Let's see what these dreams are all about. You load up one of the more recent recordings of the dreams and are met with some of the most beautiful visions you've ever seen. Something about them seemed so surreal; you could not even begin to desribe it to your coworkers without looking like a nut. Maybe, there was a reason that civilization was hidden. Ending: Trapped in a False Paradise🌴""",
        "diplo":"""You send back a friendly message, albiet a weak one given the limited access you're given. After a few weeks, the aliens respond; they declined the request for the dream access. They seem glad that their message has reached someone, but informed you not to go any further. They fear with the technology you possess that they may be overthrown by the humans. Fair enough you suppose. You almost wish there was something more you could've done to win their trust. Ending: Lost to Wonder🔮""",
        "dreams":"You send the response message. Days go by before another message returns...'Given you know about our situation, you must help us. If you want the dreams, take them.' You open the attached dream file and are met with some dreams filled with wonder and beautiful visions unlike anything you've ever seen which makes the nightmares all the more terrifying. It makes you question whether the pursuit to find this civilization was worth it. Ending: Behind the Curtains of the Xialo""",
        "peace": """High Command would send out a message the following week. Making sure to be as sure as possible to have a good connection to the aliens. They would not respond for 6 months. Suddenly, a unfamiliar ship would dock into one of the ports of your station. Panicked at first, High Command would eventually stand down to the aliens upon realizing they were here about the message. They stated they would like to be peaceful towards you, but do not seek an alliance due to fear of drawing attention to someone. They did not say who though. Who is this man? We may not want to know. Ending: The Casted Shadow over Andromeda👤""",    
        "conquer":""" High Command seemed to agree almost immeadiately and quickly sent an ultimatum out to the aliens. High Command seemed to be ready for war since the beginning. Was this their plan? The aliens responded by saying they were worried this would happen. They said if a fight is wanted, to come and get it. High Command seemed amused by this threat. The war was not pretty. Luckily, you were not one of the men that had to slaughter these creatures. In the end, you sit with a statue on the planet and eternal fame. Was it all worth it though? This fame in exchange for a once unknown species' extinction. Ending: The Dark Forest🌲""",
     "falsefame":"""This is my chance to cement myself in the history books. I snatched the drive off the desk and calm as one could be, walked toward the Alpha Delta High Command Center. You walk in, cool and collected as you could. '2nd Lt., What are you doing in here?', says the man behind the first desk. My boss. 'Sir, you are going to want to see this. I have discovered a message that the aliens sent.'
     'Well, let's see this.' He plugs it into the computer and it begans to play. You lean in as you become quite intrigued on what it will say.
     'We hope this finds you quickly. We are the Xialo Civilization. We have lived on the planet of Urailo for nearly 7000 years. As threathening as that may sound, we truly wish for no relations with the humans. For our safety, We believe there is a bigger threat that looms over us from the Rilo System. And, that our secrecy has kept us from being discovered. This message may also be our last. Rest now knowing your search was successful.'
     'Well, that might be the most poetic thing I've ever heard.', said the boss. 'I believe that'll wrap all this up. We appreciate you commitment to the people; for that you are now promoted to Captain.' He salutes and you return it. After the momentary pride, the seriousness of the message looms over you. What if that message is the only memoir that will exist of them? Ending: Memoir of a Fallen Civilization📕""",
        "trash":" You break the drive in half and toss it in the nearby recipticle. There's a since of relief. You feel as though you did what you were supposed to. That message was probably nothing, you think. There's a lot that starts to bear down on you. That could have been it. The ticket. Over the next few weeks, you watch as the search continues to nothing. You return home to your family thinking of what that message could have been about. Atleast, you are safe and you got promoted to 1st Lt. for serving on the voyage. Security is nice. Ending: Connection Terminated🖥️",
        "lakeinv":
        "You board onto a small dingie docked in the port. You push off the shore and use the small motor to pull out to the body. Luckily, there was a small sandbar that allowed you to park the boat. Upon exiting the boat, you notice a small note on the ground, covered in blood. It reads: 'The Moon shines bright tonight, Detective.' You are left with a sense of dread. He knows you're on his tail but you must find him. What does that mean though? You think for a second before sticking it in your pocket. You return to the docks with the plan to take the note for forensic testing. A hit. The prints return a Owen Abbins. He gets busted and taken in, yet something feels off. Maybe, he is just one small part of the conspriacy. Ending: The Moon Shines Bright Tonight.🌙",
        "dockowner":"""'Walk with me if you will Mr. Benns. What were you doing the night that woman was killed?'
        'Well, I was sitting behind the register. Closing up for the night, putting bills in the register, the usual.'
        'You have cameras, Mr. Benns. It would be very difficult to secure an alibi for you if you did not.'
        'My cameras broke two weeks ago; Some hoodlums came in and ransacked the place while I was out, taking care of the lake.' 
        'What did they look like?'
        'They were all dressed in these big yellow jackets with yellow masks with only eye holes. Definetly a planned attack, yet I don't know who I set off.
        Upon further investigation, you found out that the jackets and masks belong to the Society of the Waking Moon. A recent society that has popped up and been causing trouble. Maybe, this cult-like society is behind the murders. You end up finding a member and getting him to talk about the society. However, he was a relatively low ranked member and a few days later, he was found dead in his apartment. Ending: The New Moon🌑""",
    "accuse": "'Nice try', you say smirking, 'You set up the raid on your dock to cover up the alibi and to make you seem like a victim rather than a murder. You're the person who killed that woman. You have a lot of explaining to do. Upon reaching the station, the dock owner spills that he worked with some of the quarter moons to set the whole thing up, but that he wasn't the one pulling the strings. 'Keep looking Detective. I'm just a Cog in the machine. Ending: The Waning Crescent🌒""",
        "checkinbook": """ You check the names and find a name interest: 'John Ebbens Room 301' You bust in his room to find an empty room. However, it looks like he left in a hurry as there's a few things of interst left. Namely, a poster on the wall showing a hierachy of sorts. At the top there is one man with a full moon above him followed by 4 3 quarter moons and 12 new moons under split up among the quarter moons. You take the poster back to the station. 'This is our Society. Now we just have to bust them.' The next day, you are able to corner the man initially in that apartment. He says that the best way to get to the leader is through the slums. He is holed up there under the protection of Big Johnny. As for me, I served my purpose for the Moon. Ending: The Half Moon🌓""",
       "everyroom": "We can't let him get away. We begin busting through every room in the hotel, but he's already gone. The only thing we found of use is in Room 301. A note on the ground reads, 'To Shine you must find the Light.' This note feels like it's missing something. We weren't able to gather much else about the society. This feel like just a small piece to the puzzle. Ending: The Waning Moon🌘",
        "raided": "The team busts in and captures Big Johnny with relative ease. After a long, interrogation, he breaks. 'The leader of the Society of the Waking Moon is a man that goes by 'The Moon'. He is currently out in the woods performing his final ritual to ascend to Moonhood.' You are your team rush out into the middle of the Wakeborrow Woods and track down the man. He quickly notices you and begins to run. You and your team quickly encircle him. 'I see you found Big Johnny. Shame. I was beginning to like him. It seems the Moon does shine bright after all.' You arrest him and take him back to the station. You feel proud to bring the Half-Moon Murders to a close. For now. Ending: The Full Moon🌕",
        "appease": "You arrange for the money to be sent to Big Johnny in return for the location of the leader of the Society of the Waking Moon. He sends you the location of the leader. You and your team rush out into the middle of the Wakeborrow Woods and attempt to track him down. However, he is nowhere to be seen. You are left with a sense of anger. You were so close to capturing him just to be outsmarted at the very end. 'This isn't over.', you mutter as you walk back to your car. 'This is only the beginning.'Ending: Waxing Gibbous🌔",
    "nexusgatewalker":"'Well, well, well, Congrats. It's about time someone put in the effort. You know it's nice being able to share this with someone else. All these choices, all these endings, all these items. Someone has to make them; I'm glad I found someone worthy to take my spot', an older gentleman says from behind a Screen. Welcome to the team. You really earned this. Thanks for playing. ~ Byron Ending: The Nexus Gate Walker🌐"
}